[build]
  command = "cd frontend && npm run build"
  publish = "frontend/dist"
  
[build.environment]
  VITE_SUPABASE_URL = "YOUR_SUPABASE_URL"
  VITE_SUPABASE_ANON_KEY = "YOUR_SUPABASE_ANON_KEY"
  
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
